---
title: Eric Whitmire
timezone: UTC
collections:
  publications:
    title: Publications
    output: false
email: ewhitmire@meta.com
description: 'Research Scientist at Meta working at the intersection of human-computer interaction, systems, and robotics.'
baseurl: ''
url: https://ericwhitmire.com
github_username: ewhitmire
linkedin_username: ericwhitmire
google_scholar_url: https://scholar.google.com/citations?hl=en&user=DcI0h4gAAAAJ
markdown: kramdown
sass:
  load_paths:
  - _sass
exclude: ['.gitignore', 'Gemfile', 'Gemfile.lock', 'README.md']
