---
title: Eric Whitmire
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  publications:
    title: Publications
    output: false
  uploads:
    title: Uploads
    output: true
email: ewhitmire@fb.com
description: ''
baseurl: ''
url: http://ericwhitmire.com
github_username: ewhitmire
linkedin_username: ericwhitmire
markdown: kramdown
keep_files: [bower_components]
sass:
  load_paths:
  - _sass
exclude: ['.gitignore', '**/CHANGELOG.md', 'Gemfile', 'Gemfile.lock', '**/LICENSE.md', '**/README.md']
