---
title: Eric Whitmire
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  publications:
    title: Publications
    output: false
  uploads:
    title: Uploads
    output: true
email: emwhit@cs.washington.edu
description: ''
baseurl: ''
url: http://ericwhitmire.com
github_username: ewhitmire
linkedin_username: ericwhitmire
markdown: kramdown
sass:
  load_paths:
  - _sass
